In [12]:
import torch

In [13]:
a = torch.Tensor([1,2,3])
b = torch.Tensor([5,4,3])

In [14]:
a

tensor([1., 2., 3.])

In [15]:
b

tensor([5., 4., 3.])

In [16]:
add = torch.add(a,b)
add

tensor([6., 6., 6.])

In [17]:
mean = torch.mean(a)
mean

tensor(2.)

In [18]:
exp = torch.exp(b)
exp

tensor([148.4132,  54.5981,  20.0855])

In [19]:
eq  = torch.eq(a,b)
eq

tensor([False, False,  True])

In [20]:
sqrt = torch.sqrt(b)
sqrt

tensor([2.2361, 2.0000, 1.7321])

In [21]:
log = torch.log(a)
log

tensor([0.0000, 0.6931, 1.0986])

In [23]:
sub = torch.sub(a,b)
sub

tensor([-4., -2.,  0.])

In [24]:
mul = torch.mul(a,b)
mul

tensor([5., 8., 9.])

In [25]:
power = torch.pow(a,3)
power

tensor([ 1.,  8., 27.])

In [26]:
minimum = torch.min(a)
minimum

tensor(1.)

In [27]:
maxi = torch.max(b)
maxi

tensor(5.)

In [28]:
tanh =torch.tanh(a)
tanh

tensor([0.7616, 0.9640, 0.9951])